name: bangbang
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1
  cloud_functions: ^6.3.5
  firebase_database: ^12.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/wild_west_town.png
    - assets/images/role_sheriff.png
    - assets/images/role_deputy.png
    - assets/images/role_raider.png
    - assets/images/role_traitor.png
    - assets/images/role_guardian.png
    - assets/images/health_bullet.png
    - assets/images/cards/
    - assets/images/effects/
    - assets/images/role_cards/
    - assets/audio/western_theme.wav